name: Playwright Tests
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    # 1. Клонируем код репозитория
    - uses: actions/checkout@v4
    
    # 2. Ставим Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # 3. Ставим зависимости (npm install)
    - name: Install dependencies
      run: npm ci

    # 4. Ставим браузеры Playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 5. ЗАПУСК ТЕСТОВ (UI + API)
    - name: Run Playwright tests
      run: npx playwright test

    # 6. Сохраняем отчет (если тесты упали или прошли)
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30